### ISSUE TITLE
Fail to develop&build

### ISSUE THREAD

**Issue by KiichiSugihara** [airalab/robonomics-wiki#79]
# Summary
fail to develop&build command

# Error Message
```
 ERROR  Failed to compile with 6 errors                                                                                                                                                                     10:24:48

 error  in ./src/templates/DocPage.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Name "___" must not begin with "__", which is reserved by GraphQL introspection.

Name "___" must not begin with "__", which is reserved by GraphQL introspection.
    at assertValidSchema (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/graphql/type/validate.js:71:11)
    at validate (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/graphql/validation/validate.js:54:35)
    at module.exports (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/gridsome/lib/plugins/vue-components/lib/validate.js:21:10)
    at Object.module.exports (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js:30:22)

 @ ./src/templates/DocPage.vue?vue&type=custom&index=0&blockType=page-query 1:0-333 1:349-352 1:354-684 1:354-684
 @ ./src/templates/DocPage.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/templates/DocPage.vue?vue&type=custom&index=1&blockType=static-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/static-query.js):
Error: Name "___" must not begin with "__", which is reserved by GraphQL introspection.

Name "___" must not begin with "__", which is reserved by GraphQL introspection.
    at assertValidSchema (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/graphql/type/validate.js:71:11)
    at validate (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/graphql/validation/validate.js:54:35)
    at module.exports (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/gridsome/lib/plugins/vue-components/lib/validate.js:21:10)
    at Object.module.exports (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/static-query.js:35:20)

 @ ./src/templates/DocPage.vue?vue&type=custom&index=1&blockType=static-query 1:0-337 1:353-356 1:358-692 1:358-692
 @ ./src/templates/DocPage.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/components/SidebarDocs.vue?vue&type=custom&index=0&blockType=static-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/static-query.js):
Error: Name "___" must not begin with "__", which is reserved by GraphQL introspection.

Name "___" must not begin with "__", which is reserved by GraphQL introspection.
    at assertValidSchema (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/graphql/type/validate.js:71:11)
    at validate (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/graphql/validation/validate.js:54:35)
    at module.exports (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/gridsome/lib/plugins/vue-components/lib/validate.js:21:10)
    at Object.module.exports (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/static-query.js:35:20)

 @ ./src/components/SidebarDocs.vue?vue&type=custom&index=0&blockType=static-query 1:0-341 1:357-360 1:362-700 1:362-700
 @ ./src/components/SidebarDocs.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/templates/DocPage.vue?vue&type=script&lang=js&
 @ ./src/templates/DocPage.vue?vue&type=script&lang=js&
 @ ./src/templates/DocPage.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/components/ToggleLang.vue?vue&type=custom&index=0&blockType=static-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/static-query.js):
Error: Name "___" must not begin with "__", which is reserved by GraphQL introspection.

Name "___" must not begin with "__", which is reserved by GraphQL introspection.
    at assertValidSchema (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/graphql/type/validate.js:71:11)
    at validate (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/graphql/validation/validate.js:54:35)
    at module.exports (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/gridsome/lib/plugins/vue-components/lib/validate.js:21:10)
    at Object.module.exports (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/static-query.js:35:20)

 @ ./src/components/ToggleLang.vue?vue&type=custom&index=0&blockType=static-query 1:0-340 1:356-359 1:361-698 1:361-698
 @ ./src/components/ToggleLang.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Header.vue?vue&type=script&lang=js&
 @ ./src/components/Header.vue?vue&type=script&lang=js&
 @ ./src/components/Header.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/layouts/Default.vue?vue&type=script&lang=js&
 @ ./src/layouts/Default.vue?vue&type=script&lang=js&
 @ ./src/layouts/Default.vue
 @ ./src/main.js
 @ ./node_modules/gridsome/app/app.js
 @ ./node_modules/gridsome/app/entry.client.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/components/Search.vue?vue&type=custom&index=0&blockType=static-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/static-query.js):
Error: Name "___" must not begin with "__", which is reserved by GraphQL introspection.

Name "___" must not begin with "__", which is reserved by GraphQL introspection.
    at assertValidSchema (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/graphql/type/validate.js:71:11)
    at validate (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/graphql/validation/validate.js:54:35)
    at module.exports (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/gridsome/lib/plugins/vue-components/lib/validate.js:21:10)
    at Object.module.exports (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/static-query.js:35:20)

 @ ./src/components/Search.vue?vue&type=custom&index=0&blockType=static-query 1:0-336 1:352-355 1:357-690 1:357-690
 @ ./src/components/Search.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Header.vue?vue&type=script&lang=js&
 @ ./src/components/Header.vue?vue&type=script&lang=js&
 @ ./src/components/Header.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/layouts/Default.vue?vue&type=script&lang=js&
 @ ./src/layouts/Default.vue?vue&type=script&lang=js&
 @ ./src/layouts/Default.vue
 @ ./src/main.js
 @ ./node_modules/gridsome/app/app.js
 @ ./node_modules/gridsome/app/entry.client.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/components/PageNextPrev.vue?vue&type=custom&index=0&blockType=static-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/static-query.js):
Error: Name "___" must not begin with "__", which is reserved by GraphQL introspection.

Name "___" must not begin with "__", which is reserved by GraphQL introspection.
    at assertValidSchema (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/graphql/type/validate.js:71:11)
    at validate (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/graphql/validation/validate.js:54:35)
    at module.exports (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/gridsome/lib/plugins/vue-components/lib/validate.js:21:10)
    at Object.module.exports (/Users/sugiharakiichi/Desktop/robonomics-wiki/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/static-query.js:35:20)

 @ ./src/components/PageNextPrev.vue?vue&type=custom&index=0&blockType=static-query 1:0-342 1:358-361 1:363-702 1:363-702
 @ ./src/components/PageNextPrev.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/templates/DocPage.vue?vue&type=script&lang=js&
 @ ./src/templates/DocPage.vue?vue&type=script&lang=js&
 @ ./src/templates/DocPage.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

```

# Cause
- updated package?
  - After update package ,failed to build.

[![Image from Gyazo](https://i.gyazo.com/c9172aa997a3e8845c24848b05980626.png)](https://gyazo.com/c9172aa997a3e8845c24848b05980626)

**Comment by Vourhey** [comment]
Hi! After package update everything was fine, I checked it out. Most probably korean translation broke the build process. Working on it

**Comment by positivecrash** [comment]
fixed
