### ISSUE TITLE
Can't build wiki locally #2

### ISSUE THREAD

**Issue by nakata5321** [airalab/robonomics-wiki#901]
## Problem
Continue of #900. 
Now using node JS version `v20.16.0`.
```
✗ npm -v
10.8.1
➜  robonomics-wiki git:(master) ✗ node -v
v20.16.0
```

 I run `npm install` and wait until it finished. logs:
```
✗ npm install  


added 6 packages, removed 1 package, changed 1 package, and audited 587 packages in 4s

163 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (3 moderate, 5 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

However, when i try to start wiki loccaly with command `npm run start`, i've got next error:
```
✗ npm run start


> robonomics-wiki@1.0.0 start
> run-p dev:*


> robonomics-wiki@1.0.0 dev:11ty
> cross-env ELEVENTY_ENV=development --max_old_space_size=8000 eleventy --serve --watch --incremental

✘ [ERROR] No matching export in "env-ns:env" for import "GSCRIPT_ID"

    src/assets/js/components/feedback.js:2:9:
      2 │ import { GSCRIPT_ID } from 'env'
        ╵          ~~~~~~~~~~

[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble rendering js template ./src/assets/js/index.js (via TemplateContentRenderError)
[11ty] 2. Build failed with 1 error:
[11ty] src/assets/js/components/feedback.js:2:9: ERROR: No matching export in "env-ns:env" for import "GSCRIPT_ID" (via Error)
[11ty] 
[11ty] Original error stack trace: Error: Build failed with 1 error:
[11ty] src/assets/js/components/feedback.js:2:9: ERROR: No matching export in "env-ns:env" for import "GSCRIPT_ID"
[11ty]     at failureErrorWithLog (/home/nakata/robonomics-wiki/node_modules/esbuild/lib/main.js:1651:15)
[11ty]     at /home/nakata/robonomics-wiki/node_modules/esbuild/lib/main.js:1059:25
[11ty]     at runOnEndCallbacks (/home/nakata/robonomics-wiki/node_modules/esbuild/lib/main.js:1486:45)
[11ty]     at buildResponseToResult (/home/nakata/robonomics-wiki/node_modules/esbuild/lib/main.js:1057:7)
[11ty]     at /home/nakata/robonomics-wiki/node_modules/esbuild/lib/main.js:1086:16
[11ty]     at responseCallbacks.<computed> (/home/nakata/robonomics-wiki/node_modules/esbuild/lib/main.js:704:9)
[11ty]     at handleIncomingPacket (/home/nakata/robonomics-wiki/node_modules/esbuild/lib/main.js:764:9)
[11ty]     at Socket.readFromStdout (/home/nakata/robonomics-wiki/node_modules/esbuild/lib/main.js:680:7)
[11ty]     at Socket.emit (node:events:519:28)
[11ty]     at addChunk (node:internal/streams/readable:559:12)
[11ty] Copied 970 files / Wrote 0 files in 2.32 seconds (v2.0.1)
ERROR: "dev:11ty" exited with 1.
```

**Comment by zirreal** [comment]
fixed the bug and added a comment about .env file - https://wiki.robonomics.network/docs/edit-wiki/#2-serve-locally-develop-develop-m1
